// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmOfDA8NYdEPgnafqZjAWpvc5cbVASBzI',
    appId: '1:504457843646:web:a9fc2ad64a4aea8fdf9fef',
    messagingSenderId: '504457843646',
    projectId: 'socialize-muc',
    authDomain: 'socialize-muc.firebaseapp.com',
    storageBucket: 'socialize-muc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9B0UR6blkmt9jSITAo3h_8_BHbhirQIM',
    appId: '1:504457843646:android:847d58a441af16e2df9fef',
    messagingSenderId: '504457843646',
    projectId: 'socialize-muc',
    storageBucket: 'socialize-muc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigtkqtOb8iP1etj2-NQI9agVTn-6k8OE',
    appId: '1:504457843646:ios:d04b8123260172fddf9fef',
    messagingSenderId: '504457843646',
    projectId: 'socialize-muc',
    storageBucket: 'socialize-muc.firebasestorage.app',
    iosClientId: '504457843646-russ4qsfqunif0jotvj2l7o3k9qr2pbp.apps.googleusercontent.com',
    iosBundleId: 'com.hackatum.socialize.socialize',
  );
}
